uint8                       audio_task_type     # 表情任务类型 0--播放固定音频。 1: 合成音频 。 2: 删除固定音频  3：上传对话记录  4. 播放在线音频 -- 通过“string类型”
string                      fixed_audio_name    # 播放固定音频  string类型 string类型的0
string                      timbre                      # 音色 0：男  1：女生
string                      synthetic_audio_txt         # 合成音频内容
string                      synthetic_audio_title       # 合成音频标题
string                      delete_fixed_audio          # 删除固定音频
string                      play_online_audio           # 播放在线音频
