uint8                       garsp_task_type   # 抓取任务类型  0--打开物体  1--夹取物体&&吸取物体
---
bool                        success            #是否成功           
string                      message            #消息反馈  --失败原因 成功了 啥的........